name:                Hgame
version:             0.1.0.0
github:              "jeremander/Hgame"
license:             BSD3
author:              "Jeremy Silver"
maintainer:          "jeremys@nessiness.com"
copyright:           "2021 Jeremy Silver"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Hgame#readme>

dependencies:
- base >= 4.7 && < 5
- monad-loops
- monad-memo
- MonadRandom
- mtl
- split

library:
  source-dirs: src

executables:
  hgame-tictactoe:
    main: TicTacToe
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - Hgame

tests:
  Hgame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hgame
